name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: "Release"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Debug action
      uses: hmarr/debug-action@v2.0.1

    - name: Get prerelease flag
      run: echo ${{ github.event.release.prerelease }}
      
    - name: Get prerelease flag
      if: ${{ github.event.release.prerelease == true }} 
      run: echo 'Pre release'
      
    - name: Get prerelease flag1
      if: ${{ github.event.release.prerelease == false }} 
      run: echo 'Not Pre release'
      
    

    
