name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: "Release"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1

    - name: Get prerelease flag
      id: get_prerelease
      run: echo ${{ github.event.release }}
      
    

    
