name: Build and Test Pull Requests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: "Build and Test Pull Requests"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git tag --sort=taggerdate | tail -1)
    
    - name: Print Version
      run: echo ${{ steps.get_version.outputs.VERSION }}
      
      
        
        

