on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: TransactionProcessing/actions@0.0.3
        with:
          filepath: '/Testing/MainProject/MainProject.csproj'
          versionnumber: 2.0.0
