on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2.3.4
      
    - name: Hello world action step
      uses: TransactionProcessing/actions@1.0.1
      with:
        filepath: 'Testing/MainProject/MainProject.csproj'
        versionnumber: 2.0.0
